// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
    MY_KV_1: KVNamespace;
    MY_KV_2: KVNamespace;
    MY_R2: R2Bucket;
    MY_DO: DurableObjectNamespace;
    AI: AiNamespace;
    VECTORIZE: VectorizeNamespace
  }
