export const onPageLoadMarkdown = `Learn what happens when the /are-you-ai/<session-id> page is loaded:

1. Request sent through the API layer to Workers KV with list of pre-generated AI Images
2. Random image url returned back from the frontend.  
3. The request is sent to an AI worker through the Worker API and AI Gateway. The AI Worker utilizes the llava-1.5-7b-hf model to produce a textual description of the randomly generated image. Subsequently, the bge-base-en-v1.5 model is employed to generate a 768-dimension text embedding of the AI image description.  
4. The text-embedding is stored in Cloudflare's vector database.   
5. The description of the image generated by the AI is sent back to the frontend application.   
`
