export const toolTipData = {
  images: "Generated Images are stored in Cloudflare Images",
  randomImage: "Image generated by Workers AI Text to Image model",
  textEmbedding: "Text-embeddings created from user and AI descriptions",
  aiDescription: "Description generated by Workers AI Image to Text model",
  aiGateway: "AI Gateway used to have more observability into AI Workers",
  vectorize: "Vector database cosine similarity used to compare descriptions",
};
