export function getRandomPrompt() {
	const attributes = [
		'angry',
		'happy',
		'dancing',
		'sad',
		'excited',
		'frustrated',
		'tired',
		'silly',
		'gold',
		'rockstar',
		'sleeping',
		'silver',
		'biking',
		'artistic',
		'hipster',
		'cowboy',
		'hula hooping',
		'brave',
		'curious',
		'energetic',
		'grumpy',
		'jumpy',
		'lonely',
		'mysterious',
		'playful',
		'proud',
		'shy',
		'sneaky',
		'thoughtful',
		'worried',
		'zen',
		'robotic',
		'glowing',
		'transparent',
		'invisible',
		'giant',
		'tiny',
		'colorful',
		'monochrome',
		'striped',
		'spotted',
		'glittery',
		'metallic',
		'wooden',
		'plastic',
		'paper',
		'crystal',
		'fluffy',
		'scaly',
		'feathery',
		'wet',
		'dry',
		'sticky',
		'smooth',
		'rough',
		'glossy',
		'matte',
	];
	const creatures = [
		'dog',
		'cat',
		'giraffe',
		'cow',
		'sheep',
		'bee',
		'hyena',
		'lion',
		'shark',
		'alien',
		'bigfoot',
		'angel',
		'crocodile',
		'pomeranian',
		'scorpion',
		'spaghetti monster',
		'dinosaur',
		'dove',
		'sloth',
		'beetlejuice',
		'meerkat',
		'unicorn',
		'nutcracker',
		'deer',
		'turkey',
		'pony',
		'star',
		'penguin',
		'taco',
		'whale',
		'pig',
		'turtle',
		'dodo',
		'cup of coffee',
		'panda',
		'flamingo',
		'elephant',
		'kangaroo',
		'koala',
		'lemur',
		'otter',
		'platypus',
		'raccoon',
		'red panda',
		'rhinoceros',
		'squirrel',
		'tiger',
		'wolf',
		'zebra',
		'dragon',
		'phoenix',
		'griffin',
		'mermaid',
	];
	const background = [
		'in a forest',
		'in a city',
		'in a desert',
		'in a jungle',
		'in a cave',
		'in a castle',
		'in a spaceship',
		'in a submarine',
		'in a volcano',
		'in a snowstorm',
		'in a thunderstorm',
		'in a tornado',
		'in a hurricane',
		'in a blizzard',
		'in a flood',
		'in a drought',
		'in a rainbow',
		'in a sunset',
		'in a sunrise',
		'on a beach',
		'on a mountain',
		'in a meadow',
		'in a haunted house',
		'in a library',
		'in a museum',
		'in a laboratory',
		'in a garden',
		'in a park',
		'in a carnival',
		'in a circus',
		'in a zoo',
		'in a aquarium',
		'in a farm',
		'in a medieval village',
		'in a futuristic city',
		'in a parallel universe',
		'in a dream',
		'in a nightmare',
	];
	const actions = [
		'buying a house',
		'applying for a job',
		'eating a big salad',
		'celebrating christmas',
		'riding on a space ship',
		'visiting their in-laws',
		'surfing',
		'drinking milk',
		'doing laundry',
		'driving a fancy car',
		'cooking a four-course meal',
		'preparing a pizza',
		'walking a dog',
		'shoveling snow',
		'snowball fight',
		'sticking out its tongue',
		'in a haunted house',
		'making a valentine',
		'getting married',
		'going to school',
		'at the playground',
		'playing hide and seek',
		'raking leaves',
		'reading a book',
		'teaching science',
		'watching tv',
		'going to the movies',
		'building a house',
		'building a boat',
		'riding a roller coaster',
		'riding a carousel',
		'playing american football',
		'scoring a goal in soccer',
		'playing the guitar',
		'painting a masterpiece',
		'writing a novel',
		'playing chess',
		'gardening',
		'playing basketball',
		'playing video games',
		'doing yoga',
		'meditating',
		'jogging in the park',
		'playing the piano',
		'playing the violin',
		'playing the drums',
		'playing the flute',
		'playing the saxophone',
		'playing the trumpet',
		'playing the harmonica',
		'playing the accordion',
		'playing the banjo',
		'playing the ukulele',
		'playing the cello',
		'playing the harp',
		'playing the clarinet',
		'playing the triangle',
		'playing the tambourine',
		'playing the bongos',
		'playing the congas',
	];
	const style = [
		'high res photo',
		'watercolor',
		'comic book',
		'lego',
		'oil painting',
		'banksy',
		'mechanical',
		'pop art',
		"children's drawing",
		'8-bit video game',
		'book cover',
		'andy warhol',
		'collage',
		'family christmas card',
		'cyberpunk',
		'steampunk',
		'pixel art',
		'abstract',
		'minimalist',
		'vintage',
		'retro',
		'graffiti',
		'fantasy',
		'surrealism',
		'baroque',
		'renaissance',
		'modern',
		'cubism',
		'impressionism',
		'expressionism',
		'photorealism',
		'line art',
		'charcoal sketch',
		'pastel',
		'stained glass',
		'pointillism',
		'pop surrealism',
		'low poly',
		'vector art',
		'flat design',
		'geometric',
		'neon',
		'psychedelic',
		'folk art',
		'street art',
		'concept art',
		'fantasy art',
		'noir',
		'vaporwave',
		'glitch art',
		'kawaii',
		'chibi',
		'anime',
		'manga',
		'western',
		'film noir',
		'black and white',
		'sepia',
		'monochrome',
		'duotone',
		'tritone',
		'polaroid',
		'instagram filter',
		'pop culture',
	];
	return [
		'a',
		getRandomElement(attributes),
		getRandomElement(creatures),
		getRandomElement(background),
		getRandomElement(actions),
		'in the style of',
		getRandomElement(style),
	].join(' ');
}

function getRandomElement(arr: string[]): string {
	return arr[Math.floor(Math.random() * arr.length)];
}
