export function getRandomPrompt() {
	const attributes = [
		'angry',
		'happy',
		'dancing',
		'sad',
		'excited',
		'frustrated',
		'tired',
		'silly',
		'gold',
		'rockstar',
		'sleeping',
		'silver',
		'biking',
		'artistic',
		'hipster',
		'cowboy',
		'hula hooping',
	];
	const creatures = [
		'dog',
		'cat',
		'giraffe',
		'cow',
		'sheep',
		'bee',
		'hyena',
		'lion',
		'shark',
		'alien',
		'bigfoot',
		'angel',
		'crocodile',
		'pomeranian',
		'scorpion',
		'spaghetti monster',
		'dinosaur',
		'dove',
		'sloth',
		'beetlejuice',
		'meerkat',
		'unicorn',
		'nutcracker',
		'deer',
		'turkey',
		'pony',
		'star',
		'penguin',
		'taco',
		'whale',
		'pig',
		'turtle',
		'dodo',
		'cup of coffee',
		'panda',
		'flamingo',
	];
	const background = [
		'in a forest',
		'in a city',
		'in a desert',
		'in a jungle',
		'in a cave',
		'in a castle',
		'in a spaceship',
		'in a submarine',
		'in a volcano',
		'in a snowstorm',
		'in a thunderstorm',
		'in a tornado',
		'in a hurricane',
		'in a blizzard',
		'in a flood',
		'in a drought',
		'in a rainbow',
		'in a sunset',
		'in a sunrise',
	];
	const actions = [
		'buying a house',
		'applying for a job',
		'eating a big salad',
		'celebrating christmas',
		'riding on a space ship',
		'visiting their in-laws',
		'surfing',
		'drinking milk',
		'doing laundry',
		'driving a fancy car',
		'cooking a four-course meal',
		'preparing a pizza',
		'walking a dog',
		'shoveling snow',
		'snowball fight',
		'sticking out its tongue',
		'in a haunted house',
		'making a valentine',
		'getting married',
		'going to school',
		'at the playground',
		'playing hide and seek',
		'raking leaves',
		'reading a book',
		'teaching science',
		'watching tv',
		'going to the movies',
		'building a house',
		'building a boat',
		'riding a roller coaster',
		'riding a carousel',
		'playing american football',
		'scoring a goal in soccer',
	];
	const style = [
		'high res photo',
		'watercolor',
		'comic book',
		'lego',
		'oil painting',
		'banksy',
		'mechanical',
		'pop art',
		"children's drawing",
		'8-bit video game',
		'book cover',
		'andy warhol',
		'collage',
		'family christmas card',
		'cyberpunk',
	];
	return [
		'a',
		getRandomElement(attributes),
		getRandomElement(creatures),
		getRandomElement(background),
		getRandomElement(actions),
		'in the style of',
		getRandomElement(style),
	].join(' ');
}

function getRandomElement(arr: string[]): string {
	return arr[Math.floor(Math.random() * arr.length)];
}
