// Generated by Wrangler by running `wrangler types`

interface Env {
	DB: D1Database;
	VECTORIZE: VectorizeIndex;
	AI: Ai;
	KV: KVNamespace
	ai_description: KVNamespace
	are_you_ai_embeddings: KVNamespace
}
